version: '3.9'

services:
  db:
    image: postgres
    restart: always
    ports:
      - 5432:5432
    env_file:
      - .env.docker
    volumes:
      - pgdata:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}"]
      interval: 10s
      retries: 5
      start_period: 30s
      timeout: 10s
  web:
    build: .
    working_dir: /app
    command: ["/app/entrypoint.sh"]
    env_file:
      - .env.docker

    ports:
      - "8000:8000"

    volumes:
      - ./app:/app/app
      - /app/.venv
    
    depends_on:
      db:
        condition: service_healthy
        restart: true
volumes:
  pgdata: