version: '3.9'

services:
  db:
    image: postgres
    restart: always
    ports:
      - 5432:5432
    env_file:
      - .env.docker
    volumes:
      - pgdata:/var/lib/postgresql/data
  web:
    build: .
    working_dir: /app
    command: uvicorn app.main:app --host 0.0.0.0 --port 8000 --reload
    env_file:
      - .env.docker

    ports:
      - "8000:8000"

    volumes:
      - ./app:/app/app
      - /app/.venv
    
    depends_on:
      - db
volumes:
  pgdata: